"""empty message

Revision ID: 58c5c6bf7947
Revises: 
Create Date: 2021-07-30 17:43:58.001654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58c5c6bf7947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('search_type', sa.Enum('SUBMISSION', 'COMMENT', name='searchtype'), nullable=True),
    sa.Column('search_params', sa.String(length=8192), nullable=False),
    sa.Column('before', sa.DateTime(), nullable=False),
    sa.Column('after', sa.DateTime(), nullable=False),
    sa.Column('query_', sa.String(length=2048), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('blob_uri', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_params'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('reddit_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('query_', sa.String(length=2048), nullable=False),
    sa.Column('stat', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_stat')
    op.drop_table('reddit_query')
    # ### end Alembic commands ###
